
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "events"
    label: "Tournaments & Results"
    folder: "events"
    create: true
    fields:
      - { label: "Event", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Result", name: "result", widget: "string" }
